# Site settings
title: Bob's Family
email: blankbob00+family@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "family" # the subpath of your site, e.g. /blog/
url: "http://blankbob.github.io" # the base hostname & protocol for your site
twitter_username: blankbob
github_username:  blankbob

# Build settings
markdown: kramdown

paginate: 4

author: Your name

gems: [jekyll-paginate]
